/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5356e61ed2fe8879a2db82265e68f8e9)
interface __BaseEnv_Env {
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	B2_STORAGE_LIMIT_BYTES: "9000000000";
	APP_PASSWORD_HASH: string;
	SESSION_SECRET: string;
	B2_ENDPOINT: string;
	B2_BUCKET_NAME: string;
	B2_APPLICATION_KEY_ID: string;
	B2_APPLICATION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "B2_STORAGE_LIMIT_BYTES" | "APP_PASSWORD_HASH" | "SESSION_SECRET" | "B2_ENDPOINT" | "B2_BUCKET_NAME" | "B2_APPLICATION_KEY_ID" | "B2_APPLICATION_KEY">> {}
}
