/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=.env.local.example --include-runtime=false` (hash: 1ab433629e4c1b471ce9b1f9f5c08928)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	B2_STORAGE_LIMIT_BYTES: "9000000000";
	B2_ENDPOINT: string;
	B2_BUCKET_NAME: string;
	B2_APPLICATION_KEY_ID: string;
	B2_APPLICATION_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "B2_STORAGE_LIMIT_BYTES" | "B2_ENDPOINT" | "B2_BUCKET_NAME" | "B2_APPLICATION_KEY_ID" | "B2_APPLICATION_KEY">> {}
}
